server:
  port: 8000
spring:
  application:
    name: user-service

#注册服务到eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon，注意Feign和Ribbon不要重复重试，否则会产生笛卡尔积次数
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 3000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 3000
  MaxAutoRetries: 0 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试


####配置hystrix超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
### 设置fegin的超时，开启Hystrix断路器
feign:
  hystrix:
    enabled: true
  client:
    config:
      # 如果使用通用配置，携程default
      feginName:
        connectTimeout: 5000
        readTimeout: 5000 # 单位ms