server:
  port: 6666

#注册服务到eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hack-feng/Spring-Cloud-Edgware.git
          search-paths: /config
          # 这里用的是公有库，无需密码，如果是私有库，需设置密码
          username:
          password:
      label: master